"""Generate synthetic test fixtures for plate detector evaluation.

Creates programmatic images with known plate-like regions and writes
bounding-box ground truth to a JSON file.  No real vehicle images are
used — all fixtures are synthetic to guarantee legal reuse.

Usage:
    python scripts/generate_test_fixtures.py
    python scripts/generate_test_fixtures.py --output sample-data/evaluation
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    sys.exit("Pillow is required: pip install Pillow")


def _draw_plate(
    draw: ImageDraw.ImageDraw,
    x1: int,
    y1: int,
    width: int,
    height: int,
    bg_color: str,
    text_color: str,
    text: str,
) -> dict:
    """Draw a plate-like rectangle and return bounding-box ground truth."""

    x2, y2 = x1 + width, y1 + height
    draw.rectangle([x1, y1, x2, y2], fill=bg_color, outline="black", width=2)

    # Center text inside the plate rectangle.
    try:
        font = ImageFont.truetype("arial.ttf", max(12, height // 3))
    except OSError:
        font = ImageFont.load_default()

    text_bbox = draw.textbbox((0, 0), text, font=font)
    tw, th = text_bbox[2] - text_bbox[0], text_bbox[3] - text_bbox[1]
    tx = x1 + (width - tw) // 2
    ty = y1 + (height - th) // 2
    draw.text((tx, ty), text, fill=text_color, font=font)

    return {"x1": x1, "y1": y1, "x2": x2, "y2": y2, "text": text}


def generate_synthetic_plate_white(output_dir: Path) -> dict:
    """White plate with black text on a neutral background."""

    img = Image.new("RGB", (640, 480), color=(120, 130, 140))
    draw = ImageDraw.Draw(img)
    # Vehicle body
    draw.rectangle([100, 150, 540, 430], fill=(60, 60, 80))
    bbox = _draw_plate(draw, 220, 320, 200, 50, "white", "black", "YGN 5A-1234")
    path = output_dir / "synthetic_plate_white.png"
    img.save(path)
    return {
        "file": path.name,
        "width": img.width,
        "height": img.height,
        "expected_detections": 1,
        "bounding_boxes": [bbox],
        "source": "project-generated by scripts/generate_test_fixtures.py",
        "license": "project educational use; see sample-data/evaluation/README.md",
    }


def generate_synthetic_plate_yellow(output_dir: Path) -> dict:
    """Yellow plate with dark text."""

    img = Image.new("RGB", (640, 480), color=(80, 100, 60))
    draw = ImageDraw.Draw(img)
    draw.rectangle([80, 120, 560, 440], fill=(50, 50, 70))
    bbox = _draw_plate(draw, 200, 340, 220, 55, "#FFD700", "#1a1a2e", "MDY 3B-5678")
    path = output_dir / "synthetic_plate_yellow.png"
    img.save(path)
    return {
        "file": path.name,
        "width": img.width,
        "height": img.height,
        "expected_detections": 1,
        "bounding_boxes": [bbox],
        "source": "project-generated by scripts/generate_test_fixtures.py",
        "license": "project educational use; see sample-data/evaluation/README.md",
    }


def generate_synthetic_no_plate(output_dir: Path) -> dict:
    """Plain scene with no plate-like region."""

    img = Image.new("RGB", (640, 480), color=(100, 150, 200))
    draw = ImageDraw.Draw(img)
    # Trees / nature — no rectangles
    draw.ellipse([50, 100, 250, 350], fill=(30, 120, 50))
    draw.ellipse([300, 80, 550, 380], fill=(40, 130, 60))
    draw.rectangle([0, 400, 640, 480], fill=(80, 60, 40))
    path = output_dir / "synthetic_no_plate.png"
    img.save(path)
    return {
        "file": path.name,
        "width": img.width,
        "height": img.height,
        "expected_detections": 0,
        "bounding_boxes": [],
        "source": "project-generated by scripts/generate_test_fixtures.py",
        "license": "project educational use; see sample-data/evaluation/README.md",
    }


def generate_synthetic_multi_plate(output_dir: Path) -> dict:
    """Two vehicles / two plate-like regions."""

    img = Image.new("RGB", (800, 480), color=(130, 130, 130))
    draw = ImageDraw.Draw(img)
    # Vehicle 1 (left)
    draw.rectangle([30, 150, 360, 430], fill=(70, 30, 30))
    bbox1 = _draw_plate(draw, 120, 340, 180, 45, "white", "black", "SGN 1C-9012")
    # Vehicle 2 (right)
    draw.rectangle([420, 150, 770, 430], fill=(30, 30, 70))
    bbox2 = _draw_plate(draw, 520, 340, 180, 45, "white", "black", "NPT 2D-3456")
    path = output_dir / "synthetic_multi_plate.png"
    img.save(path)
    return {
        "file": path.name,
        "width": img.width,
        "height": img.height,
        "expected_detections": 2,
        "bounding_boxes": [bbox1, bbox2],
        "source": "project-generated by scripts/generate_test_fixtures.py",
        "license": "project educational use; see sample-data/evaluation/README.md",
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate synthetic plate detection test fixtures."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("sample-data/evaluation"),
        help="Directory to write fixture images and ground truth (default: sample-data/evaluation)",
    )
    args = parser.parse_args()

    output_dir: Path = args.output
    output_dir.mkdir(parents=True, exist_ok=True)

    ground_truth: list[dict] = []
    generators = [
        generate_synthetic_plate_white,
        generate_synthetic_plate_yellow,
        generate_synthetic_no_plate,
        generate_synthetic_multi_plate,
    ]

    for gen in generators:
        entry = gen(output_dir)
        ground_truth.append(entry)
        status = f"{entry['expected_detections']} detection(s)"
        print(f"  Created {entry['file']:40s} [{status}]")

    gt_path = output_dir / "ground_truth.json"
    gt_path.write_text(json.dumps(ground_truth, indent=2), encoding="utf-8")
    print(f"\n  Ground truth written to {gt_path}")
    print(f"  Total fixtures: {len(ground_truth)}")


if __name__ == "__main__":
    main()
